services:
  postgres-db:
    image: postgres:15-alpine
    container_name: postgres-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234$
      POSTGRES_DB: ShopQuanAo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - shop-network

  backend-api:
    build: 
      context: ./Backend/BanQuanAo  # Chỉ chính xác vào nơi có file pom.xml và Dockerfile Java
    container_name: backend-container
    ports:
      - "8080:8080"
    depends_on:
      - postgres-db
    networks:
      - shop-network

  frontend-web:
    build: 
      context: ./FrontEnd/Asm12/AsmFrontend  # Chỉ chính xác vào nơi có package.json và Dockerfile VueJS
    container_name: frontend-container
    ports:
      - "80:80"
    depends_on:
      - backend-api
    networks:
      - shop-network

volumes:
  postgres_data:

networks:
  shop-network:
    driver: bridge